# workflow name
name: Deploy

# 当有 push 到仓库和外部触发的时候就运行
on: [push, repository_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
          TZ: Asia/Shanghai
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: true
                  fetch-depth: 0
            
            - name: Install Dependencies
              run: |
                  npm install @cloudflare/kv-asset-handler --prefix ./workers-site

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2.6.0
              with:
                  hugo-version: latest
                  extended: true

            - name: Build Web
              run: hugo --gc --minify

            - name: Run Pagefind
              run: npm_config_yes=true npx pagefind --source "public"

            - name: Deploy to Cloudflare Workers
              uses: cloudflare/wrangler-action@2.0.0
              with:
                apiToken: ${{ secrets.CF_WORKERS_TOKEN }}