name: Deploy
on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 18
      - name: Run install
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - name: Build
        run: yarn run docs:build
      - uses: actions/configure-pages@v3.0.6
      - uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: docs/.vitepress/dist
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.2
